environment:
  global:
    TOXENV: py

  matrix:
    - PYTHON: C:\Python38-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -U tox

build: false

test_script:
  - python -m tox

branches:
  only:
    - master
    - standalone

cache:
  - '%LOCALAPPDATA%\pip\Cache'
