environment:
  global:
    TOXENV: py

  matrix:
    - PYTHON: C:\Python38
    - PYTHON: C:\Python38-x64

init:
  - SET PATH=%PYTHON%;%PATH%
  - SET PATH=%USERPROFILE%\.pyenv\pyenv-win\bin;%PATH%
  - SET PATH=%USERPROFILE%\.pyenv\pyenv-win\shims;%PATH%

install:
  - python --version
  - pip3 install pyenv-win --upgrade --target %USERPROFILE%/.pyenv
  - pyenv install --skip-existing
  - pip3 install -U pipenv --upgrade
  - pipenv install --dev --ignore-pipfile

build: false

test_script:
  - pipenv run nosetests

branches:
  only:
    - master
    - standalone

cache:
  - '%LOCALAPPDATA%\pip\Cache'
